// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.vsphere;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.vsphere.FolderArgs;
import com.pulumi.vsphere.Utilities;
import com.pulumi.vsphere.inputs.FolderState;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * The `vsphere.Folder` resource can be used to manage vSphere inventory folders.
 * The resource supports creating folders of the 5 major types - datacenter
 * folders, host and cluster folders, virtual machine folders, storage folders,
 * and network folders.
 * 
 * Paths are always relative to the specific type of folder you are creating.
 * A subfolder is discovered by parsing the relative path specified in `path`, so
 * `foo/bar` will create a folder named `bar` in the parent folder `foo`, as long
 * as the folder `foo` exists.
 * 
 * ## Example Usage
 * 
 * The basic example below creates a virtual machine folder named
 * `example-vm-folder` in the default datacenter&#39;s VM hierarchy.
 * 
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.vsphere.VsphereFunctions;
 * import com.pulumi.vsphere.inputs.GetDatacenterArgs;
 * import com.pulumi.vsphere.Folder;
 * import com.pulumi.vsphere.FolderArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         final var datacenter = VsphereFunctions.getDatacenter(GetDatacenterArgs.builder()
 *             .name(vsphereDatacenter)
 *             .build());
 * 
 *         var vmFolder = new Folder("vmFolder", FolderArgs.builder()
 *             .path("example-vm-folder")
 *             .type("vm")
 *             .datacenterId(datacenter.id())
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * 
 * ### Example with Sub-folders
 * 
 * The below example builds off of the above by first creating a folder named
 * `example-parent-vm-folder`, and then locating `example-child-vm-folder` in that
 * folder. To ensure the parent is created first, we create an interpolation
 * dependency off the parent&#39;s `path` attribute.
 * 
 * Note that if you change parents (for example, went from the above basic
 * configuration to this one), your folder will be moved to be under the correct
 * parent.
 * 
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.vsphere.VsphereFunctions;
 * import com.pulumi.vsphere.inputs.GetDatacenterArgs;
 * import com.pulumi.vsphere.Folder;
 * import com.pulumi.vsphere.FolderArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         final var datacenter = VsphereFunctions.getDatacenter(GetDatacenterArgs.builder()
 *             .name(vsphereDatacenter)
 *             .build());
 * 
 *         var parent = new Folder("parent", FolderArgs.builder()
 *             .path("example-parent-vm-folder")
 *             .type("vm")
 *             .datacenterId(datacenter.id())
 *             .build());
 * 
 *         var child = new Folder("child", FolderArgs.builder()
 *             .path(parent.path().applyValue(_path -> String.format("%s/example-child-vm-folder", _path)))
 *             .type("vm")
 *             .datacenterId(datacenter.id())
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * 
 * ## Import
 * 
 * An existing folder can be imported into this resource via
 * its full path, via the following command:
 * 
 * [docs-import]: https://developer.hashicorp.com/terraform/cli/import
 * 
 * ```sh
 * $ pulumi import vsphere:index/folder:Folder folder /default-dc/vm/example-vm-folder
 * ```
 * 
 * The above command would import the folder from our examples above, the VM
 * folder named `example-vm-folder` located in the datacenter named
 * `default-dc`.
 * 
 */
@ResourceType(type="vsphere:index/folder:Folder")
public class Folder extends com.pulumi.resources.CustomResource {
    /**
     * Map of custom attribute ids to attribute
     * value strings to set for folder. See [here][docs-setting-custom-attributes]
     * for a reference on how to set values for custom attributes.
     * 
     * [docs-setting-custom-attributes]: /docs/providers/vsphere/r/custom_attribute.html#using-custom-attributes-in-a-supported-resource
     * 
     * &gt; **NOTE:** Custom attributes are unsupported on direct ESXi connections
     * and require vCenter.
     * 
     */
    @Export(name="customAttributes", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> customAttributes;

    /**
     * @return Map of custom attribute ids to attribute
     * value strings to set for folder. See [here][docs-setting-custom-attributes]
     * for a reference on how to set values for custom attributes.
     * 
     * [docs-setting-custom-attributes]: /docs/providers/vsphere/r/custom_attribute.html#using-custom-attributes-in-a-supported-resource
     * 
     * &gt; **NOTE:** Custom attributes are unsupported on direct ESXi connections
     * and require vCenter.
     * 
     */
    public Output<Optional<Map<String,String>>> customAttributes() {
        return Codegen.optional(this.customAttributes);
    }
    /**
     * The ID of the datacenter the folder will be created in.
     * Required for all folder types except for datacenter folders. Forces a new
     * resource if changed.
     * 
     */
    @Export(name="datacenterId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> datacenterId;

    /**
     * @return The ID of the datacenter the folder will be created in.
     * Required for all folder types except for datacenter folders. Forces a new
     * resource if changed.
     * 
     */
    public Output<Optional<String>> datacenterId() {
        return Codegen.optional(this.datacenterId);
    }
    /**
     * The path of the folder to be created. This is relative to
     * the root of the type of folder you are creating, and the supplied datacenter.
     * For example, given a default datacenter of `default-dc`, a folder of type
     * `vm` (denoting a virtual machine folder), and a supplied folder of
     * `example-vm-folder`, the resulting path would be
     * `/default-dc/vm/example-vm-folder`.
     * 
     * When working with nested datacenters, note that references to these folders in data sources
     * will require the full path including the parent datacenter folder path, as shown in the
     * nested datacenter example above.
     * 
     * &gt; **NOTE:** `path` can be modified - the resulting behavior is dependent on
     * what section of `path` you are modifying. If you are modifying the parent (so
     * any part before the last `/`), your folder will be moved to that new parent. If
     * modifying the name (the part after the last `/`), your folder will be renamed.
     * 
     */
    @Export(name="path", refs={String.class}, tree="[0]")
    private Output<String> path;

    /**
     * @return The path of the folder to be created. This is relative to
     * the root of the type of folder you are creating, and the supplied datacenter.
     * For example, given a default datacenter of `default-dc`, a folder of type
     * `vm` (denoting a virtual machine folder), and a supplied folder of
     * `example-vm-folder`, the resulting path would be
     * `/default-dc/vm/example-vm-folder`.
     * 
     * When working with nested datacenters, note that references to these folders in data sources
     * will require the full path including the parent datacenter folder path, as shown in the
     * nested datacenter example above.
     * 
     * &gt; **NOTE:** `path` can be modified - the resulting behavior is dependent on
     * what section of `path` you are modifying. If you are modifying the parent (so
     * any part before the last `/`), your folder will be moved to that new parent. If
     * modifying the name (the part after the last `/`), your folder will be renamed.
     * 
     */
    public Output<String> path() {
        return this.path;
    }
    /**
     * The IDs of any tags to attach to this resource. See
     * [here][docs-applying-tags] for a reference on how to apply tags.
     * 
     * [docs-applying-tags]: /docs/providers/vsphere/r/tag.html#using-tags-in-a-supported-resource
     * 
     */
    @Export(name="tags", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> tags;

    /**
     * @return The IDs of any tags to attach to this resource. See
     * [here][docs-applying-tags] for a reference on how to apply tags.
     * 
     * [docs-applying-tags]: /docs/providers/vsphere/r/tag.html#using-tags-in-a-supported-resource
     * 
     */
    public Output<Optional<List<String>>> tags() {
        return Codegen.optional(this.tags);
    }
    /**
     * The type of folder to create. Allowed options are
     * `datacenter` for datacenter folders, `host` for host and cluster folders,
     * `vm` for virtual machine folders, `datastore` for datastore folders, and
     * `network` for network folders. Forces a new resource if changed.
     * 
     */
    @Export(name="type", refs={String.class}, tree="[0]")
    private Output<String> type;

    /**
     * @return The type of folder to create. Allowed options are
     * `datacenter` for datacenter folders, `host` for host and cluster folders,
     * `vm` for virtual machine folders, `datastore` for datastore folders, and
     * `network` for network folders. Forces a new resource if changed.
     * 
     */
    public Output<String> type() {
        return this.type;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Folder(java.lang.String name) {
        this(name, FolderArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Folder(java.lang.String name, FolderArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Folder(java.lang.String name, FolderArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("vsphere:index/folder:Folder", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Folder(java.lang.String name, Output<java.lang.String> id, @Nullable FolderState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("vsphere:index/folder:Folder", name, state, makeResourceOptions(options, id), false);
    }

    private static FolderArgs makeArgs(FolderArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? FolderArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Folder get(java.lang.String name, Output<java.lang.String> id, @Nullable FolderState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Folder(name, id, state, options);
    }
}
