// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.VSphere.Outputs
{

    [OutputType]
    public sealed class OfflineSoftwareDepotComponent
    {
        /// <summary>
        /// The name of the component. Useful for easier identification.
        /// </summary>
        public readonly string? DisplayName;
        /// <summary>
        /// The identifier of the component.
        /// </summary>
        public readonly string? Key;
        /// <summary>
        /// The list of available versions of the component.
        /// </summary>
        public readonly ImmutableArray<string> Versions;

        [OutputConstructor]
        private OfflineSoftwareDepotComponent(
            string? displayName,

            string? key,

            ImmutableArray<string> versions)
        {
            DisplayName = displayName;
            Key = key;
            Versions = versions;
        }
    }
}
