// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.VSphere.Outputs
{

    [OutputType]
    public sealed class SupervisorV2WorkloadsEdgeFoundationDeploymentTarget
    {
        /// <summary>
        /// Configures the availability level for the load balancer.
        /// </summary>
        public readonly string? Availability;
        /// <summary>
        /// Determines the CPU/memory resource size of the load balancer deployment.
        /// </summary>
        public readonly string? DeploymentSize;
        /// <summary>
        /// Storage Policy containing datastores hosting the load balancer nodes.
        /// </summary>
        public readonly string? StoragePolicy;
        /// <summary>
        /// A list of vSphere Zones to enable the Supervisor on. Conflicts with `Cluster`.
        /// 
        /// &lt;a id="nestedblock--control-plane"&gt;&lt;/a&gt;
        /// </summary>
        public readonly ImmutableArray<string> Zones;

        [OutputConstructor]
        private SupervisorV2WorkloadsEdgeFoundationDeploymentTarget(
            string? availability,

            string? deploymentSize,

            string? storagePolicy,

            ImmutableArray<string> zones)
        {
            Availability = availability;
            DeploymentSize = deploymentSize;
            StoragePolicy = storagePolicy;
            Zones = zones;
        }
    }
}
