// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.VSphere.Outputs
{

    [OutputType]
    public sealed class VirtualMachineOvfDeploy
    {
        public readonly bool? AllowUnverifiedSslCert;
        public readonly string? DiskProvisioning;
        public readonly string? IpAllocationPolicy;
        public readonly string? IpProtocol;
        public readonly string? LocalOvfPath;
        public readonly ImmutableDictionary<string, string>? OvfNetworkMap;
        public readonly string? RemoteOvfUrl;

        [OutputConstructor]
        private VirtualMachineOvfDeploy(
            bool? allowUnverifiedSslCert,

            string? diskProvisioning,

            string? ipAllocationPolicy,

            string? ipProtocol,

            string? localOvfPath,

            ImmutableDictionary<string, string>? ovfNetworkMap,

            string? remoteOvfUrl)
        {
            AllowUnverifiedSslCert = allowUnverifiedSslCert;
            DiskProvisioning = diskProvisioning;
            IpAllocationPolicy = ipAllocationPolicy;
            IpProtocol = ipProtocol;
            LocalOvfPath = localOvfPath;
            OvfNetworkMap = ovfNetworkMap;
            RemoteOvfUrl = remoteOvfUrl;
        }
    }
}
