// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.vsphere.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class SupervisorV2WorkloadsNetworkNsxVpcDefaultPrivateCidr {
    /**
     * @return The starting IPv4 address of the CIDR block.
     * 
     */
    private String address;
    /**
     * @return The number of addresses in the CIDR block.
     * 
     */
    private Integer prefix;

    private SupervisorV2WorkloadsNetworkNsxVpcDefaultPrivateCidr() {}
    /**
     * @return The starting IPv4 address of the CIDR block.
     * 
     */
    public String address() {
        return this.address;
    }
    /**
     * @return The number of addresses in the CIDR block.
     * 
     */
    public Integer prefix() {
        return this.prefix;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SupervisorV2WorkloadsNetworkNsxVpcDefaultPrivateCidr defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String address;
        private Integer prefix;
        public Builder() {}
        public Builder(SupervisorV2WorkloadsNetworkNsxVpcDefaultPrivateCidr defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.address = defaults.address;
    	      this.prefix = defaults.prefix;
        }

        @CustomType.Setter
        public Builder address(String address) {
            if (address == null) {
              throw new MissingRequiredPropertyException("SupervisorV2WorkloadsNetworkNsxVpcDefaultPrivateCidr", "address");
            }
            this.address = address;
            return this;
        }
        @CustomType.Setter
        public Builder prefix(Integer prefix) {
            if (prefix == null) {
              throw new MissingRequiredPropertyException("SupervisorV2WorkloadsNetworkNsxVpcDefaultPrivateCidr", "prefix");
            }
            this.prefix = prefix;
            return this;
        }
        public SupervisorV2WorkloadsNetworkNsxVpcDefaultPrivateCidr build() {
            final var _resultValue = new SupervisorV2WorkloadsNetworkNsxVpcDefaultPrivateCidr();
            _resultValue.address = address;
            _resultValue.prefix = prefix;
            return _resultValue;
        }
    }
}
