# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['AlarmArgs', 'Alarm']

@pulumi.input_type
class AlarmArgs:
    def __init__(__self__, *,
                 description: pulumi.Input[_builtins.str],
                 entity_id: pulumi.Input[_builtins.str],
                 entity_type: pulumi.Input[_builtins.str],
                 advanced_actions: pulumi.Input[Optional[Sequence[pulumi.Input['AlarmAdvancedActionArgs']]]] = None,
                 email_actions: pulumi.Input[Optional[Sequence[pulumi.Input['AlarmEmailActionArgs']]]] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 event_expressions: pulumi.Input[Optional[Sequence[pulumi.Input['AlarmEventExpressionArgs']]]] = None,
                 expression_operator: pulumi.Input[Optional[_builtins.str]] = None,
                 metric_expressions: pulumi.Input[Optional[Sequence[pulumi.Input['AlarmMetricExpressionArgs']]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 snmp_actions: pulumi.Input[Optional[Sequence[pulumi.Input['AlarmSnmpActionArgs']]]] = None,
                 state_expressions: pulumi.Input[Optional[Sequence[pulumi.Input['AlarmStateExpressionArgs']]]] = None):
        """
        The set of arguments for constructing a Alarm resource.

        :param pulumi.Input[_builtins.str] description: The alarm description.
        :param pulumi.Input[_builtins.str] entity_id: The [managed object reference ID][docs-about-morefs] of the entity the alarm will be created in.
        :param pulumi.Input[_builtins.str] entity_type: The type of the entity the alarm will be created in.
        :param pulumi.Input[Sequence[pulumi.Input['AlarmAdvancedActionArgs']]] advanced_actions: Advanced alarm action to trigger depending on the alarm state, such as entering maintenance mode.
        :param pulumi.Input[Sequence[pulumi.Input['AlarmEmailActionArgs']]] email_actions: Email alarm action to trigger depending on the alarm state.
        :param pulumi.Input[_builtins.bool] enabled: Whether or not the alarm is enabled.
        :param pulumi.Input[Sequence[pulumi.Input['AlarmEventExpressionArgs']]] event_expressions: Alarm trigger expressions based on events.
        :param pulumi.Input[_builtins.str] expression_operator: The logical link between expressions.
        :param pulumi.Input[Sequence[pulumi.Input['AlarmMetricExpressionArgs']]] metric_expressions: Alarm trigger expressions based on metric values.
        :param pulumi.Input[_builtins.str] name: The name of the alarm. This name needs to be unique
               within the vCenter. Forces a new resource if changed.
        :param pulumi.Input[Sequence[pulumi.Input['AlarmSnmpActionArgs']]] snmp_actions: Snmp alarm action to trigger depending on the alarm state.
        :param pulumi.Input[Sequence[pulumi.Input['AlarmStateExpressionArgs']]] state_expressions: Alarm trigger expressions based on object state changes.
        """
        pulumi.set(__self__, "description", description)
        pulumi.set(__self__, "entity_id", entity_id)
        pulumi.set(__self__, "entity_type", entity_type)
        if advanced_actions is not None:
            pulumi.set(__self__, "advanced_actions", advanced_actions)
        if email_actions is not None:
            pulumi.set(__self__, "email_actions", email_actions)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if event_expressions is not None:
            pulumi.set(__self__, "event_expressions", event_expressions)
        if expression_operator is not None:
            pulumi.set(__self__, "expression_operator", expression_operator)
        if metric_expressions is not None:
            pulumi.set(__self__, "metric_expressions", metric_expressions)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if snmp_actions is not None:
            pulumi.set(__self__, "snmp_actions", snmp_actions)
        if state_expressions is not None:
            pulumi.set(__self__, "state_expressions", state_expressions)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[_builtins.str]:
        """
        The alarm description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="entityId")
    def entity_id(self) -> pulumi.Input[_builtins.str]:
        """
        The [managed object reference ID][docs-about-morefs] of the entity the alarm will be created in.
        """
        return pulumi.get(self, "entity_id")

    @entity_id.setter
    def entity_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "entity_id", value)

    @_builtins.property
    @pulumi.getter(name="entityType")
    def entity_type(self) -> pulumi.Input[_builtins.str]:
        """
        The type of the entity the alarm will be created in.
        """
        return pulumi.get(self, "entity_type")

    @entity_type.setter
    def entity_type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "entity_type", value)

    @_builtins.property
    @pulumi.getter(name="advancedActions")
    def advanced_actions(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['AlarmAdvancedActionArgs']]]]:
        """
        Advanced alarm action to trigger depending on the alarm state, such as entering maintenance mode.
        """
        return pulumi.get(self, "advanced_actions")

    @advanced_actions.setter
    def advanced_actions(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['AlarmAdvancedActionArgs']]]]):
        pulumi.set(self, "advanced_actions", value)

    @_builtins.property
    @pulumi.getter(name="emailActions")
    def email_actions(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['AlarmEmailActionArgs']]]]:
        """
        Email alarm action to trigger depending on the alarm state.
        """
        return pulumi.get(self, "email_actions")

    @email_actions.setter
    def email_actions(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['AlarmEmailActionArgs']]]]):
        pulumi.set(self, "email_actions", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether or not the alarm is enabled.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter(name="eventExpressions")
    def event_expressions(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['AlarmEventExpressionArgs']]]]:
        """
        Alarm trigger expressions based on events.
        """
        return pulumi.get(self, "event_expressions")

    @event_expressions.setter
    def event_expressions(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['AlarmEventExpressionArgs']]]]):
        pulumi.set(self, "event_expressions", value)

    @_builtins.property
    @pulumi.getter(name="expressionOperator")
    def expression_operator(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The logical link between expressions.
        """
        return pulumi.get(self, "expression_operator")

    @expression_operator.setter
    def expression_operator(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "expression_operator", value)

    @_builtins.property
    @pulumi.getter(name="metricExpressions")
    def metric_expressions(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['AlarmMetricExpressionArgs']]]]:
        """
        Alarm trigger expressions based on metric values.
        """
        return pulumi.get(self, "metric_expressions")

    @metric_expressions.setter
    def metric_expressions(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['AlarmMetricExpressionArgs']]]]):
        pulumi.set(self, "metric_expressions", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the alarm. This name needs to be unique
        within the vCenter. Forces a new resource if changed.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="snmpActions")
    def snmp_actions(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['AlarmSnmpActionArgs']]]]:
        """
        Snmp alarm action to trigger depending on the alarm state.
        """
        return pulumi.get(self, "snmp_actions")

    @snmp_actions.setter
    def snmp_actions(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['AlarmSnmpActionArgs']]]]):
        pulumi.set(self, "snmp_actions", value)

    @_builtins.property
    @pulumi.getter(name="stateExpressions")
    def state_expressions(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['AlarmStateExpressionArgs']]]]:
        """
        Alarm trigger expressions based on object state changes.
        """
        return pulumi.get(self, "state_expressions")

    @state_expressions.setter
    def state_expressions(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['AlarmStateExpressionArgs']]]]):
        pulumi.set(self, "state_expressions", value)


@pulumi.input_type
class _AlarmState:
    def __init__(__self__, *,
                 advanced_actions: pulumi.Input[Optional[Sequence[pulumi.Input['AlarmAdvancedActionArgs']]]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 email_actions: pulumi.Input[Optional[Sequence[pulumi.Input['AlarmEmailActionArgs']]]] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 entity_id: pulumi.Input[Optional[_builtins.str]] = None,
                 entity_type: pulumi.Input[Optional[_builtins.str]] = None,
                 event_expressions: pulumi.Input[Optional[Sequence[pulumi.Input['AlarmEventExpressionArgs']]]] = None,
                 expression_operator: pulumi.Input[Optional[_builtins.str]] = None,
                 metric_expressions: pulumi.Input[Optional[Sequence[pulumi.Input['AlarmMetricExpressionArgs']]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 snmp_actions: pulumi.Input[Optional[Sequence[pulumi.Input['AlarmSnmpActionArgs']]]] = None,
                 state_expressions: pulumi.Input[Optional[Sequence[pulumi.Input['AlarmStateExpressionArgs']]]] = None):
        """
        Input properties used for looking up and filtering Alarm resources.

        :param pulumi.Input[Sequence[pulumi.Input['AlarmAdvancedActionArgs']]] advanced_actions: Advanced alarm action to trigger depending on the alarm state, such as entering maintenance mode.
        :param pulumi.Input[_builtins.str] description: The alarm description.
        :param pulumi.Input[Sequence[pulumi.Input['AlarmEmailActionArgs']]] email_actions: Email alarm action to trigger depending on the alarm state.
        :param pulumi.Input[_builtins.bool] enabled: Whether or not the alarm is enabled.
        :param pulumi.Input[_builtins.str] entity_id: The [managed object reference ID][docs-about-morefs] of the entity the alarm will be created in.
        :param pulumi.Input[_builtins.str] entity_type: The type of the entity the alarm will be created in.
        :param pulumi.Input[Sequence[pulumi.Input['AlarmEventExpressionArgs']]] event_expressions: Alarm trigger expressions based on events.
        :param pulumi.Input[_builtins.str] expression_operator: The logical link between expressions.
        :param pulumi.Input[Sequence[pulumi.Input['AlarmMetricExpressionArgs']]] metric_expressions: Alarm trigger expressions based on metric values.
        :param pulumi.Input[_builtins.str] name: The name of the alarm. This name needs to be unique
               within the vCenter. Forces a new resource if changed.
        :param pulumi.Input[Sequence[pulumi.Input['AlarmSnmpActionArgs']]] snmp_actions: Snmp alarm action to trigger depending on the alarm state.
        :param pulumi.Input[Sequence[pulumi.Input['AlarmStateExpressionArgs']]] state_expressions: Alarm trigger expressions based on object state changes.
        """
        if advanced_actions is not None:
            pulumi.set(__self__, "advanced_actions", advanced_actions)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if email_actions is not None:
            pulumi.set(__self__, "email_actions", email_actions)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if entity_id is not None:
            pulumi.set(__self__, "entity_id", entity_id)
        if entity_type is not None:
            pulumi.set(__self__, "entity_type", entity_type)
        if event_expressions is not None:
            pulumi.set(__self__, "event_expressions", event_expressions)
        if expression_operator is not None:
            pulumi.set(__self__, "expression_operator", expression_operator)
        if metric_expressions is not None:
            pulumi.set(__self__, "metric_expressions", metric_expressions)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if snmp_actions is not None:
            pulumi.set(__self__, "snmp_actions", snmp_actions)
        if state_expressions is not None:
            pulumi.set(__self__, "state_expressions", state_expressions)

    @_builtins.property
    @pulumi.getter(name="advancedActions")
    def advanced_actions(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['AlarmAdvancedActionArgs']]]]:
        """
        Advanced alarm action to trigger depending on the alarm state, such as entering maintenance mode.
        """
        return pulumi.get(self, "advanced_actions")

    @advanced_actions.setter
    def advanced_actions(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['AlarmAdvancedActionArgs']]]]):
        pulumi.set(self, "advanced_actions", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The alarm description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="emailActions")
    def email_actions(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['AlarmEmailActionArgs']]]]:
        """
        Email alarm action to trigger depending on the alarm state.
        """
        return pulumi.get(self, "email_actions")

    @email_actions.setter
    def email_actions(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['AlarmEmailActionArgs']]]]):
        pulumi.set(self, "email_actions", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether or not the alarm is enabled.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter(name="entityId")
    def entity_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The [managed object reference ID][docs-about-morefs] of the entity the alarm will be created in.
        """
        return pulumi.get(self, "entity_id")

    @entity_id.setter
    def entity_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "entity_id", value)

    @_builtins.property
    @pulumi.getter(name="entityType")
    def entity_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The type of the entity the alarm will be created in.
        """
        return pulumi.get(self, "entity_type")

    @entity_type.setter
    def entity_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "entity_type", value)

    @_builtins.property
    @pulumi.getter(name="eventExpressions")
    def event_expressions(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['AlarmEventExpressionArgs']]]]:
        """
        Alarm trigger expressions based on events.
        """
        return pulumi.get(self, "event_expressions")

    @event_expressions.setter
    def event_expressions(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['AlarmEventExpressionArgs']]]]):
        pulumi.set(self, "event_expressions", value)

    @_builtins.property
    @pulumi.getter(name="expressionOperator")
    def expression_operator(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The logical link between expressions.
        """
        return pulumi.get(self, "expression_operator")

    @expression_operator.setter
    def expression_operator(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "expression_operator", value)

    @_builtins.property
    @pulumi.getter(name="metricExpressions")
    def metric_expressions(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['AlarmMetricExpressionArgs']]]]:
        """
        Alarm trigger expressions based on metric values.
        """
        return pulumi.get(self, "metric_expressions")

    @metric_expressions.setter
    def metric_expressions(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['AlarmMetricExpressionArgs']]]]):
        pulumi.set(self, "metric_expressions", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the alarm. This name needs to be unique
        within the vCenter. Forces a new resource if changed.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="snmpActions")
    def snmp_actions(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['AlarmSnmpActionArgs']]]]:
        """
        Snmp alarm action to trigger depending on the alarm state.
        """
        return pulumi.get(self, "snmp_actions")

    @snmp_actions.setter
    def snmp_actions(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['AlarmSnmpActionArgs']]]]):
        pulumi.set(self, "snmp_actions", value)

    @_builtins.property
    @pulumi.getter(name="stateExpressions")
    def state_expressions(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['AlarmStateExpressionArgs']]]]:
        """
        Alarm trigger expressions based on object state changes.
        """
        return pulumi.get(self, "state_expressions")

    @state_expressions.setter
    def state_expressions(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['AlarmStateExpressionArgs']]]]):
        pulumi.set(self, "state_expressions", value)


@pulumi.type_token("vsphere:index/alarm:Alarm")
class Alarm(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 advanced_actions: pulumi.Input[Optional[Sequence[pulumi.Input[Union['AlarmAdvancedActionArgs', 'AlarmAdvancedActionArgsDict']]]]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 email_actions: pulumi.Input[Optional[Sequence[pulumi.Input[Union['AlarmEmailActionArgs', 'AlarmEmailActionArgsDict']]]]] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 entity_id: pulumi.Input[Optional[_builtins.str]] = None,
                 entity_type: pulumi.Input[Optional[_builtins.str]] = None,
                 event_expressions: pulumi.Input[Optional[Sequence[pulumi.Input[Union['AlarmEventExpressionArgs', 'AlarmEventExpressionArgsDict']]]]] = None,
                 expression_operator: pulumi.Input[Optional[_builtins.str]] = None,
                 metric_expressions: pulumi.Input[Optional[Sequence[pulumi.Input[Union['AlarmMetricExpressionArgs', 'AlarmMetricExpressionArgsDict']]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 snmp_actions: pulumi.Input[Optional[Sequence[pulumi.Input[Union['AlarmSnmpActionArgs', 'AlarmSnmpActionArgsDict']]]]] = None,
                 state_expressions: pulumi.Input[Optional[Sequence[pulumi.Input[Union['AlarmStateExpressionArgs', 'AlarmStateExpressionArgsDict']]]]] = None,
                 __props__=None):
        """
        Provides a VMware vSphere alarm resource. This can be used deployed on all kinds of vSphere inventory objects.

        ## Example Usage

        ### S

        **Create warning alarm with an email action on a datacenter when on a host is disconnected:**

        ```python
        import pulumi
        import pulumi_vsphere as vsphere

        host_disconnected_warning = vsphere.Alarm("host_disconnected_warning",
            name="Host disconnected",
            description="Triggers a warning when a host is disconnected",
            entity_type="Datacenter",
            entity_id=datacenter["id"],
            state_expressions=[{
                "operator": "isEqual",
                "state_path": "runtime.connectionState",
                "object_type": "HostSystem",
                "yellow": "disconnected",
            }],
            email_actions=[{
                "to": "foo@example.com",
                "subject": "Host disconnected",
                "start_state": "green",
                "final_state": "yellow",
            }])
        ```

        **Create critical alarm when a host CPU usage is above 95% for 5min:**

        ```python
        import pulumi
        import pulumi_vsphere as vsphere

        host_disconnected_warning = vsphere.Alarm("host_disconnected_warning",
            name="Host CPU usage",
            description="Triggers a critical when a host CPU usage is too high",
            entity_type="Datacenter",
            entity_id=datacenter["id"],
            metric_expressions=[{
                "metric_counter_id": 2,
                "operator": "isAbove",
                "object_type": "HostSystem",
                "red": 9500,
                "red_interval": 300,
            }])
        ```

        **Create alarm to set a host in maintenance when a lacp down event occurs, and remove the maintenance when the lacp is up again:**

        ```python
        import pulumi
        import pulumi_vsphere as vsphere

        lacp_down_on_host = vsphere.Alarm("lacp_down_on_host",
            name="LACP down on host",
            description="Set the host is maintenance if lacp goes down",
            entity_type="Datacenter",
            entity_id=datacenter["id"],
            event_expressions=[
                {
                    "event_type_id": "esx.problem.net.lacp.lag.transition.down",
                    "object_type": "HostSystem",
                    "status": "red",
                },
                {
                    "event_type_id": "esx.problem.net.lacp.lag.transition.up",
                    "object_type": "HostSystem",
                    "status": "green",
                },
            ],
            advanced_actions=[
                {
                    "start_state": "green",
                    "final_state": "red",
                    "name": "EnterMaintenanceMode_Task",
                },
                {
                    "start_state": "red",
                    "final_state": "green",
                    "name": "ExitMaintenanceMode_Task",
                },
            ])
        ```

        ## Import

        Importing vSphere alarm is not managed.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[Union['AlarmAdvancedActionArgs', 'AlarmAdvancedActionArgsDict']]]] advanced_actions: Advanced alarm action to trigger depending on the alarm state, such as entering maintenance mode.
        :param pulumi.Input[_builtins.str] description: The alarm description.
        :param pulumi.Input[Sequence[pulumi.Input[Union['AlarmEmailActionArgs', 'AlarmEmailActionArgsDict']]]] email_actions: Email alarm action to trigger depending on the alarm state.
        :param pulumi.Input[_builtins.bool] enabled: Whether or not the alarm is enabled.
        :param pulumi.Input[_builtins.str] entity_id: The [managed object reference ID][docs-about-morefs] of the entity the alarm will be created in.
        :param pulumi.Input[_builtins.str] entity_type: The type of the entity the alarm will be created in.
        :param pulumi.Input[Sequence[pulumi.Input[Union['AlarmEventExpressionArgs', 'AlarmEventExpressionArgsDict']]]] event_expressions: Alarm trigger expressions based on events.
        :param pulumi.Input[_builtins.str] expression_operator: The logical link between expressions.
        :param pulumi.Input[Sequence[pulumi.Input[Union['AlarmMetricExpressionArgs', 'AlarmMetricExpressionArgsDict']]]] metric_expressions: Alarm trigger expressions based on metric values.
        :param pulumi.Input[_builtins.str] name: The name of the alarm. This name needs to be unique
               within the vCenter. Forces a new resource if changed.
        :param pulumi.Input[Sequence[pulumi.Input[Union['AlarmSnmpActionArgs', 'AlarmSnmpActionArgsDict']]]] snmp_actions: Snmp alarm action to trigger depending on the alarm state.
        :param pulumi.Input[Sequence[pulumi.Input[Union['AlarmStateExpressionArgs', 'AlarmStateExpressionArgsDict']]]] state_expressions: Alarm trigger expressions based on object state changes.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: AlarmArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Provides a VMware vSphere alarm resource. This can be used deployed on all kinds of vSphere inventory objects.

        ## Example Usage

        ### S

        **Create warning alarm with an email action on a datacenter when on a host is disconnected:**

        ```python
        import pulumi
        import pulumi_vsphere as vsphere

        host_disconnected_warning = vsphere.Alarm("host_disconnected_warning",
            name="Host disconnected",
            description="Triggers a warning when a host is disconnected",
            entity_type="Datacenter",
            entity_id=datacenter["id"],
            state_expressions=[{
                "operator": "isEqual",
                "state_path": "runtime.connectionState",
                "object_type": "HostSystem",
                "yellow": "disconnected",
            }],
            email_actions=[{
                "to": "foo@example.com",
                "subject": "Host disconnected",
                "start_state": "green",
                "final_state": "yellow",
            }])
        ```

        **Create critical alarm when a host CPU usage is above 95% for 5min:**

        ```python
        import pulumi
        import pulumi_vsphere as vsphere

        host_disconnected_warning = vsphere.Alarm("host_disconnected_warning",
            name="Host CPU usage",
            description="Triggers a critical when a host CPU usage is too high",
            entity_type="Datacenter",
            entity_id=datacenter["id"],
            metric_expressions=[{
                "metric_counter_id": 2,
                "operator": "isAbove",
                "object_type": "HostSystem",
                "red": 9500,
                "red_interval": 300,
            }])
        ```

        **Create alarm to set a host in maintenance when a lacp down event occurs, and remove the maintenance when the lacp is up again:**

        ```python
        import pulumi
        import pulumi_vsphere as vsphere

        lacp_down_on_host = vsphere.Alarm("lacp_down_on_host",
            name="LACP down on host",
            description="Set the host is maintenance if lacp goes down",
            entity_type="Datacenter",
            entity_id=datacenter["id"],
            event_expressions=[
                {
                    "event_type_id": "esx.problem.net.lacp.lag.transition.down",
                    "object_type": "HostSystem",
                    "status": "red",
                },
                {
                    "event_type_id": "esx.problem.net.lacp.lag.transition.up",
                    "object_type": "HostSystem",
                    "status": "green",
                },
            ],
            advanced_actions=[
                {
                    "start_state": "green",
                    "final_state": "red",
                    "name": "EnterMaintenanceMode_Task",
                },
                {
                    "start_state": "red",
                    "final_state": "green",
                    "name": "ExitMaintenanceMode_Task",
                },
            ])
        ```

        ## Import

        Importing vSphere alarm is not managed.


        :param str resource_name: The name of the resource.
        :param AlarmArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(AlarmArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 advanced_actions: pulumi.Input[Optional[Sequence[pulumi.Input[Union['AlarmAdvancedActionArgs', 'AlarmAdvancedActionArgsDict']]]]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 email_actions: pulumi.Input[Optional[Sequence[pulumi.Input[Union['AlarmEmailActionArgs', 'AlarmEmailActionArgsDict']]]]] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 entity_id: pulumi.Input[Optional[_builtins.str]] = None,
                 entity_type: pulumi.Input[Optional[_builtins.str]] = None,
                 event_expressions: pulumi.Input[Optional[Sequence[pulumi.Input[Union['AlarmEventExpressionArgs', 'AlarmEventExpressionArgsDict']]]]] = None,
                 expression_operator: pulumi.Input[Optional[_builtins.str]] = None,
                 metric_expressions: pulumi.Input[Optional[Sequence[pulumi.Input[Union['AlarmMetricExpressionArgs', 'AlarmMetricExpressionArgsDict']]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 snmp_actions: pulumi.Input[Optional[Sequence[pulumi.Input[Union['AlarmSnmpActionArgs', 'AlarmSnmpActionArgsDict']]]]] = None,
                 state_expressions: pulumi.Input[Optional[Sequence[pulumi.Input[Union['AlarmStateExpressionArgs', 'AlarmStateExpressionArgsDict']]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = AlarmArgs.__new__(AlarmArgs)

            __props__.__dict__["advanced_actions"] = advanced_actions
            if description is None and not opts.urn:
                raise TypeError("Missing required property 'description'")
            __props__.__dict__["description"] = description
            __props__.__dict__["email_actions"] = email_actions
            __props__.__dict__["enabled"] = enabled
            if entity_id is None and not opts.urn:
                raise TypeError("Missing required property 'entity_id'")
            __props__.__dict__["entity_id"] = entity_id
            if entity_type is None and not opts.urn:
                raise TypeError("Missing required property 'entity_type'")
            __props__.__dict__["entity_type"] = entity_type
            __props__.__dict__["event_expressions"] = event_expressions
            __props__.__dict__["expression_operator"] = expression_operator
            __props__.__dict__["metric_expressions"] = metric_expressions
            __props__.__dict__["name"] = name
            __props__.__dict__["snmp_actions"] = snmp_actions
            __props__.__dict__["state_expressions"] = state_expressions
        super(Alarm, __self__).__init__(
            'vsphere:index/alarm:Alarm',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            advanced_actions: pulumi.Input[Optional[Sequence[pulumi.Input[Union['AlarmAdvancedActionArgs', 'AlarmAdvancedActionArgsDict']]]]] = None,
            description: pulumi.Input[Optional[_builtins.str]] = None,
            email_actions: pulumi.Input[Optional[Sequence[pulumi.Input[Union['AlarmEmailActionArgs', 'AlarmEmailActionArgsDict']]]]] = None,
            enabled: pulumi.Input[Optional[_builtins.bool]] = None,
            entity_id: pulumi.Input[Optional[_builtins.str]] = None,
            entity_type: pulumi.Input[Optional[_builtins.str]] = None,
            event_expressions: pulumi.Input[Optional[Sequence[pulumi.Input[Union['AlarmEventExpressionArgs', 'AlarmEventExpressionArgsDict']]]]] = None,
            expression_operator: pulumi.Input[Optional[_builtins.str]] = None,
            metric_expressions: pulumi.Input[Optional[Sequence[pulumi.Input[Union['AlarmMetricExpressionArgs', 'AlarmMetricExpressionArgsDict']]]]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            snmp_actions: pulumi.Input[Optional[Sequence[pulumi.Input[Union['AlarmSnmpActionArgs', 'AlarmSnmpActionArgsDict']]]]] = None,
            state_expressions: pulumi.Input[Optional[Sequence[pulumi.Input[Union['AlarmStateExpressionArgs', 'AlarmStateExpressionArgsDict']]]]] = None) -> 'Alarm':
        """
        Get an existing Alarm resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[Union['AlarmAdvancedActionArgs', 'AlarmAdvancedActionArgsDict']]]] advanced_actions: Advanced alarm action to trigger depending on the alarm state, such as entering maintenance mode.
        :param pulumi.Input[_builtins.str] description: The alarm description.
        :param pulumi.Input[Sequence[pulumi.Input[Union['AlarmEmailActionArgs', 'AlarmEmailActionArgsDict']]]] email_actions: Email alarm action to trigger depending on the alarm state.
        :param pulumi.Input[_builtins.bool] enabled: Whether or not the alarm is enabled.
        :param pulumi.Input[_builtins.str] entity_id: The [managed object reference ID][docs-about-morefs] of the entity the alarm will be created in.
        :param pulumi.Input[_builtins.str] entity_type: The type of the entity the alarm will be created in.
        :param pulumi.Input[Sequence[pulumi.Input[Union['AlarmEventExpressionArgs', 'AlarmEventExpressionArgsDict']]]] event_expressions: Alarm trigger expressions based on events.
        :param pulumi.Input[_builtins.str] expression_operator: The logical link between expressions.
        :param pulumi.Input[Sequence[pulumi.Input[Union['AlarmMetricExpressionArgs', 'AlarmMetricExpressionArgsDict']]]] metric_expressions: Alarm trigger expressions based on metric values.
        :param pulumi.Input[_builtins.str] name: The name of the alarm. This name needs to be unique
               within the vCenter. Forces a new resource if changed.
        :param pulumi.Input[Sequence[pulumi.Input[Union['AlarmSnmpActionArgs', 'AlarmSnmpActionArgsDict']]]] snmp_actions: Snmp alarm action to trigger depending on the alarm state.
        :param pulumi.Input[Sequence[pulumi.Input[Union['AlarmStateExpressionArgs', 'AlarmStateExpressionArgsDict']]]] state_expressions: Alarm trigger expressions based on object state changes.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _AlarmState.__new__(_AlarmState)

        __props__.__dict__["advanced_actions"] = advanced_actions
        __props__.__dict__["description"] = description
        __props__.__dict__["email_actions"] = email_actions
        __props__.__dict__["enabled"] = enabled
        __props__.__dict__["entity_id"] = entity_id
        __props__.__dict__["entity_type"] = entity_type
        __props__.__dict__["event_expressions"] = event_expressions
        __props__.__dict__["expression_operator"] = expression_operator
        __props__.__dict__["metric_expressions"] = metric_expressions
        __props__.__dict__["name"] = name
        __props__.__dict__["snmp_actions"] = snmp_actions
        __props__.__dict__["state_expressions"] = state_expressions
        return Alarm(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="advancedActions")
    def advanced_actions(self) -> pulumi.Output[Optional[Sequence['outputs.AlarmAdvancedAction']]]:
        """
        Advanced alarm action to trigger depending on the alarm state, such as entering maintenance mode.
        """
        return pulumi.get(self, "advanced_actions")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[_builtins.str]:
        """
        The alarm description.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="emailActions")
    def email_actions(self) -> pulumi.Output[Optional[Sequence['outputs.AlarmEmailAction']]]:
        """
        Email alarm action to trigger depending on the alarm state.
        """
        return pulumi.get(self, "email_actions")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether or not the alarm is enabled.
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter(name="entityId")
    def entity_id(self) -> pulumi.Output[_builtins.str]:
        """
        The [managed object reference ID][docs-about-morefs] of the entity the alarm will be created in.
        """
        return pulumi.get(self, "entity_id")

    @_builtins.property
    @pulumi.getter(name="entityType")
    def entity_type(self) -> pulumi.Output[_builtins.str]:
        """
        The type of the entity the alarm will be created in.
        """
        return pulumi.get(self, "entity_type")

    @_builtins.property
    @pulumi.getter(name="eventExpressions")
    def event_expressions(self) -> pulumi.Output[Optional[Sequence['outputs.AlarmEventExpression']]]:
        """
        Alarm trigger expressions based on events.
        """
        return pulumi.get(self, "event_expressions")

    @_builtins.property
    @pulumi.getter(name="expressionOperator")
    def expression_operator(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The logical link between expressions.
        """
        return pulumi.get(self, "expression_operator")

    @_builtins.property
    @pulumi.getter(name="metricExpressions")
    def metric_expressions(self) -> pulumi.Output[Optional[Sequence['outputs.AlarmMetricExpression']]]:
        """
        Alarm trigger expressions based on metric values.
        """
        return pulumi.get(self, "metric_expressions")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the alarm. This name needs to be unique
        within the vCenter. Forces a new resource if changed.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="snmpActions")
    def snmp_actions(self) -> pulumi.Output[Optional[Sequence['outputs.AlarmSnmpAction']]]:
        """
        Snmp alarm action to trigger depending on the alarm state.
        """
        return pulumi.get(self, "snmp_actions")

    @_builtins.property
    @pulumi.getter(name="stateExpressions")
    def state_expressions(self) -> pulumi.Output[Optional[Sequence['outputs.AlarmStateExpression']]]:
        """
        Alarm trigger expressions based on object state changes.
        """
        return pulumi.get(self, "state_expressions")

