# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetAlarmResult',
    'AwaitableGetAlarmResult',
    'get_alarm',
    'get_alarm_output',
]

@pulumi.output_type
class GetAlarmResult:
    """
    A collection of values returned by getAlarm.
    """
    def __init__(__self__, advanced_actions=None, description=None, email_actions=None, enabled=None, entity_id=None, entity_type=None, event_expressions=None, expression_operator=None, id=None, metric_expressions=None, name=None, snmp_actions=None, state_expressions=None):
        if advanced_actions and not isinstance(advanced_actions, list):
            raise TypeError("Expected argument 'advanced_actions' to be a list")
        pulumi.set(__self__, "advanced_actions", advanced_actions)
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if email_actions and not isinstance(email_actions, list):
            raise TypeError("Expected argument 'email_actions' to be a list")
        pulumi.set(__self__, "email_actions", email_actions)
        if enabled and not isinstance(enabled, bool):
            raise TypeError("Expected argument 'enabled' to be a bool")
        pulumi.set(__self__, "enabled", enabled)
        if entity_id and not isinstance(entity_id, str):
            raise TypeError("Expected argument 'entity_id' to be a str")
        pulumi.set(__self__, "entity_id", entity_id)
        if entity_type and not isinstance(entity_type, str):
            raise TypeError("Expected argument 'entity_type' to be a str")
        pulumi.set(__self__, "entity_type", entity_type)
        if event_expressions and not isinstance(event_expressions, list):
            raise TypeError("Expected argument 'event_expressions' to be a list")
        pulumi.set(__self__, "event_expressions", event_expressions)
        if expression_operator and not isinstance(expression_operator, str):
            raise TypeError("Expected argument 'expression_operator' to be a str")
        pulumi.set(__self__, "expression_operator", expression_operator)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if metric_expressions and not isinstance(metric_expressions, list):
            raise TypeError("Expected argument 'metric_expressions' to be a list")
        pulumi.set(__self__, "metric_expressions", metric_expressions)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if snmp_actions and not isinstance(snmp_actions, list):
            raise TypeError("Expected argument 'snmp_actions' to be a list")
        pulumi.set(__self__, "snmp_actions", snmp_actions)
        if state_expressions and not isinstance(state_expressions, list):
            raise TypeError("Expected argument 'state_expressions' to be a list")
        pulumi.set(__self__, "state_expressions", state_expressions)

    @_builtins.property
    @pulumi.getter(name="advancedActions")
    def advanced_actions(self) -> Sequence['outputs.GetAlarmAdvancedActionResult']:
        """
        The advanced actions of the alarm.
        """
        return pulumi.get(self, "advanced_actions")

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="emailActions")
    def email_actions(self) -> Sequence['outputs.GetAlarmEmailActionResult']:
        """
        The email alarm actions of the alarm.
        """
        return pulumi.get(self, "email_actions")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> _builtins.bool:
        """
        Whether or not the alarm is enabled.
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter(name="entityId")
    def entity_id(self) -> _builtins.str:
        return pulumi.get(self, "entity_id")

    @_builtins.property
    @pulumi.getter(name="entityType")
    def entity_type(self) -> _builtins.str:
        return pulumi.get(self, "entity_type")

    @_builtins.property
    @pulumi.getter(name="eventExpressions")
    def event_expressions(self) -> Sequence['outputs.GetAlarmEventExpressionResult']:
        """
        The event expressions of the alarm.
        """
        return pulumi.get(self, "event_expressions")

    @_builtins.property
    @pulumi.getter(name="expressionOperator")
    def expression_operator(self) -> _builtins.str:
        """
        The logical link between expressions.
        """
        return pulumi.get(self, "expression_operator")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="metricExpressions")
    def metric_expressions(self) -> Optional[Sequence['outputs.GetAlarmMetricExpressionResult']]:
        """
        The metric expressions of the alarm.
        """
        return pulumi.get(self, "metric_expressions")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="snmpActions")
    def snmp_actions(self) -> Optional[Sequence['outputs.GetAlarmSnmpActionResult']]:
        """
        The snmp alarm actions of the alarm.
        """
        return pulumi.get(self, "snmp_actions")

    @_builtins.property
    @pulumi.getter(name="stateExpressions")
    def state_expressions(self) -> Optional[Sequence['outputs.GetAlarmStateExpressionResult']]:
        """
        The state expressions of the alarm.
        """
        return pulumi.get(self, "state_expressions")


class AwaitableGetAlarmResult(GetAlarmResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetAlarmResult(
            advanced_actions=self.advanced_actions,
            description=self.description,
            email_actions=self.email_actions,
            enabled=self.enabled,
            entity_id=self.entity_id,
            entity_type=self.entity_type,
            event_expressions=self.event_expressions,
            expression_operator=self.expression_operator,
            id=self.id,
            metric_expressions=self.metric_expressions,
            name=self.name,
            snmp_actions=self.snmp_actions,
            state_expressions=self.state_expressions)


def get_alarm(entity_id: Optional[_builtins.str] = None,
              entity_type: Optional[_builtins.str] = None,
              metric_expressions: Optional[Sequence[Union['GetAlarmMetricExpressionArgs', 'GetAlarmMetricExpressionArgsDict']]] = None,
              name: Optional[_builtins.str] = None,
              snmp_actions: Optional[Sequence[Union['GetAlarmSnmpActionArgs', 'GetAlarmSnmpActionArgsDict']]] = None,
              state_expressions: Optional[Sequence[Union['GetAlarmStateExpressionArgs', 'GetAlarmStateExpressionArgsDict']]] = None,
              opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetAlarmResult:
    """
    The `Alarm` data source can be used to retrieve the property of a given alarm.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_vsphere as vsphere

    datacenter = vsphere.get_datacenter(name="dc-01")
    alarm = vsphere.get_alarm(entity_type="Datacenter",
        entity_id=dc["id"],
        name="example")
    ```


    :param _builtins.str entity_id: The [managed object reference ID][docs-about-morefs] of the entity the alarm will be created in.
    :param _builtins.str entity_type: The type of the entity the alarm will be created in.
    :param Sequence[Union['GetAlarmMetricExpressionArgs', 'GetAlarmMetricExpressionArgsDict']] metric_expressions: The metric expressions of the alarm.
    :param _builtins.str name: The name of the host group.
    :param Sequence[Union['GetAlarmSnmpActionArgs', 'GetAlarmSnmpActionArgsDict']] snmp_actions: The snmp alarm actions of the alarm.
    :param Sequence[Union['GetAlarmStateExpressionArgs', 'GetAlarmStateExpressionArgsDict']] state_expressions: The state expressions of the alarm.
    """
    __args__ = dict()
    __args__['entityId'] = entity_id
    __args__['entityType'] = entity_type
    __args__['metricExpressions'] = metric_expressions
    __args__['name'] = name
    __args__['snmpActions'] = snmp_actions
    __args__['stateExpressions'] = state_expressions
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('vsphere:index/getAlarm:getAlarm', __args__, opts=opts, typ=GetAlarmResult).value

    return AwaitableGetAlarmResult(
        advanced_actions=pulumi.get(__ret__, 'advanced_actions'),
        description=pulumi.get(__ret__, 'description'),
        email_actions=pulumi.get(__ret__, 'email_actions'),
        enabled=pulumi.get(__ret__, 'enabled'),
        entity_id=pulumi.get(__ret__, 'entity_id'),
        entity_type=pulumi.get(__ret__, 'entity_type'),
        event_expressions=pulumi.get(__ret__, 'event_expressions'),
        expression_operator=pulumi.get(__ret__, 'expression_operator'),
        id=pulumi.get(__ret__, 'id'),
        metric_expressions=pulumi.get(__ret__, 'metric_expressions'),
        name=pulumi.get(__ret__, 'name'),
        snmp_actions=pulumi.get(__ret__, 'snmp_actions'),
        state_expressions=pulumi.get(__ret__, 'state_expressions'))
def get_alarm_output(entity_id: pulumi.Input[Optional[_builtins.str]] = None,
                     entity_type: pulumi.Input[Optional[_builtins.str]] = None,
                     metric_expressions: pulumi.Input[Optional[Optional[Sequence[Union['GetAlarmMetricExpressionArgs', 'GetAlarmMetricExpressionArgsDict']]]]] = None,
                     name: pulumi.Input[Optional[_builtins.str]] = None,
                     snmp_actions: pulumi.Input[Optional[Optional[Sequence[Union['GetAlarmSnmpActionArgs', 'GetAlarmSnmpActionArgsDict']]]]] = None,
                     state_expressions: pulumi.Input[Optional[Optional[Sequence[Union['GetAlarmStateExpressionArgs', 'GetAlarmStateExpressionArgsDict']]]]] = None,
                     opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetAlarmResult]:
    """
    The `Alarm` data source can be used to retrieve the property of a given alarm.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_vsphere as vsphere

    datacenter = vsphere.get_datacenter(name="dc-01")
    alarm = vsphere.get_alarm(entity_type="Datacenter",
        entity_id=dc["id"],
        name="example")
    ```


    :param _builtins.str entity_id: The [managed object reference ID][docs-about-morefs] of the entity the alarm will be created in.
    :param _builtins.str entity_type: The type of the entity the alarm will be created in.
    :param Sequence[Union['GetAlarmMetricExpressionArgs', 'GetAlarmMetricExpressionArgsDict']] metric_expressions: The metric expressions of the alarm.
    :param _builtins.str name: The name of the host group.
    :param Sequence[Union['GetAlarmSnmpActionArgs', 'GetAlarmSnmpActionArgsDict']] snmp_actions: The snmp alarm actions of the alarm.
    :param Sequence[Union['GetAlarmStateExpressionArgs', 'GetAlarmStateExpressionArgsDict']] state_expressions: The state expressions of the alarm.
    """
    __args__ = dict()
    __args__['entityId'] = entity_id
    __args__['entityType'] = entity_type
    __args__['metricExpressions'] = metric_expressions
    __args__['name'] = name
    __args__['snmpActions'] = snmp_actions
    __args__['stateExpressions'] = state_expressions
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('vsphere:index/getAlarm:getAlarm', __args__, opts=opts, typ=GetAlarmResult)
    return __ret__.apply(lambda __response__: GetAlarmResult(
        advanced_actions=pulumi.get(__response__, 'advanced_actions'),
        description=pulumi.get(__response__, 'description'),
        email_actions=pulumi.get(__response__, 'email_actions'),
        enabled=pulumi.get(__response__, 'enabled'),
        entity_id=pulumi.get(__response__, 'entity_id'),
        entity_type=pulumi.get(__response__, 'entity_type'),
        event_expressions=pulumi.get(__response__, 'event_expressions'),
        expression_operator=pulumi.get(__response__, 'expression_operator'),
        id=pulumi.get(__response__, 'id'),
        metric_expressions=pulumi.get(__response__, 'metric_expressions'),
        name=pulumi.get(__response__, 'name'),
        snmp_actions=pulumi.get(__response__, 'snmp_actions'),
        state_expressions=pulumi.get(__response__, 'state_expressions')))
