// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.vsphere.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;


public final class SupervisorV2WorkloadsKubeApiServerOptionsSecurityArgs extends com.pulumi.resources.ResourceArgs {

    public static final SupervisorV2WorkloadsKubeApiServerOptionsSecurityArgs Empty = new SupervisorV2WorkloadsKubeApiServerOptionsSecurityArgs();

    /**
     * List of DNS names to include in the certificate.
     * 
     */
    @Import(name="certificateDnsNames", required=true)
    private Output<List<String>> certificateDnsNames;

    /**
     * @return List of DNS names to include in the certificate.
     * 
     */
    public Output<List<String>> certificateDnsNames() {
        return this.certificateDnsNames;
    }

    private SupervisorV2WorkloadsKubeApiServerOptionsSecurityArgs() {}

    private SupervisorV2WorkloadsKubeApiServerOptionsSecurityArgs(SupervisorV2WorkloadsKubeApiServerOptionsSecurityArgs $) {
        this.certificateDnsNames = $.certificateDnsNames;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SupervisorV2WorkloadsKubeApiServerOptionsSecurityArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SupervisorV2WorkloadsKubeApiServerOptionsSecurityArgs $;

        public Builder() {
            $ = new SupervisorV2WorkloadsKubeApiServerOptionsSecurityArgs();
        }

        public Builder(SupervisorV2WorkloadsKubeApiServerOptionsSecurityArgs defaults) {
            $ = new SupervisorV2WorkloadsKubeApiServerOptionsSecurityArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param certificateDnsNames List of DNS names to include in the certificate.
         * 
         * @return builder
         * 
         */
        public Builder certificateDnsNames(Output<List<String>> certificateDnsNames) {
            $.certificateDnsNames = certificateDnsNames;
            return this;
        }

        /**
         * @param certificateDnsNames List of DNS names to include in the certificate.
         * 
         * @return builder
         * 
         */
        public Builder certificateDnsNames(List<String> certificateDnsNames) {
            return certificateDnsNames(Output.of(certificateDnsNames));
        }

        /**
         * @param certificateDnsNames List of DNS names to include in the certificate.
         * 
         * @return builder
         * 
         */
        public Builder certificateDnsNames(String... certificateDnsNames) {
            return certificateDnsNames(List.of(certificateDnsNames));
        }

        public SupervisorV2WorkloadsKubeApiServerOptionsSecurityArgs build() {
            if ($.certificateDnsNames == null) {
                throw new MissingRequiredPropertyException("SupervisorV2WorkloadsKubeApiServerOptionsSecurityArgs", "certificateDnsNames");
            }
            return $;
        }
    }

}
