// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.vsphere.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.vsphere.inputs.SupervisorV2ControlPlaneNetworkIpManagementIpAssignmentRangeArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SupervisorV2ControlPlaneNetworkIpManagementIpAssignmentArgs extends com.pulumi.resources.ResourceArgs {

    public static final SupervisorV2ControlPlaneNetworkIpManagementIpAssignmentArgs Empty = new SupervisorV2ControlPlaneNetworkIpManagementIpAssignmentArgs();

    /**
     * The type of the assignee.
     * 
     */
    @Import(name="assignee")
    private @Nullable Output<String> assignee;

    /**
     * @return The type of the assignee.
     * 
     */
    public Optional<Output<String>> assignee() {
        return Optional.ofNullable(this.assignee);
    }

    /**
     * The available IP addresses that can be consumed by Supervisor to run the cluster.
     * 
     */
    @Import(name="ranges")
    private @Nullable Output<List<SupervisorV2ControlPlaneNetworkIpManagementIpAssignmentRangeArgs>> ranges;

    /**
     * @return The available IP addresses that can be consumed by Supervisor to run the cluster.
     * 
     */
    public Optional<Output<List<SupervisorV2ControlPlaneNetworkIpManagementIpAssignmentRangeArgs>>> ranges() {
        return Optional.ofNullable(this.ranges);
    }

    private SupervisorV2ControlPlaneNetworkIpManagementIpAssignmentArgs() {}

    private SupervisorV2ControlPlaneNetworkIpManagementIpAssignmentArgs(SupervisorV2ControlPlaneNetworkIpManagementIpAssignmentArgs $) {
        this.assignee = $.assignee;
        this.ranges = $.ranges;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SupervisorV2ControlPlaneNetworkIpManagementIpAssignmentArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SupervisorV2ControlPlaneNetworkIpManagementIpAssignmentArgs $;

        public Builder() {
            $ = new SupervisorV2ControlPlaneNetworkIpManagementIpAssignmentArgs();
        }

        public Builder(SupervisorV2ControlPlaneNetworkIpManagementIpAssignmentArgs defaults) {
            $ = new SupervisorV2ControlPlaneNetworkIpManagementIpAssignmentArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param assignee The type of the assignee.
         * 
         * @return builder
         * 
         */
        public Builder assignee(@Nullable Output<String> assignee) {
            $.assignee = assignee;
            return this;
        }

        /**
         * @param assignee The type of the assignee.
         * 
         * @return builder
         * 
         */
        public Builder assignee(String assignee) {
            return assignee(Output.of(assignee));
        }

        /**
         * @param ranges The available IP addresses that can be consumed by Supervisor to run the cluster.
         * 
         * @return builder
         * 
         */
        public Builder ranges(@Nullable Output<List<SupervisorV2ControlPlaneNetworkIpManagementIpAssignmentRangeArgs>> ranges) {
            $.ranges = ranges;
            return this;
        }

        /**
         * @param ranges The available IP addresses that can be consumed by Supervisor to run the cluster.
         * 
         * @return builder
         * 
         */
        public Builder ranges(List<SupervisorV2ControlPlaneNetworkIpManagementIpAssignmentRangeArgs> ranges) {
            return ranges(Output.of(ranges));
        }

        /**
         * @param ranges The available IP addresses that can be consumed by Supervisor to run the cluster.
         * 
         * @return builder
         * 
         */
        public Builder ranges(SupervisorV2ControlPlaneNetworkIpManagementIpAssignmentRangeArgs... ranges) {
            return ranges(List.of(ranges));
        }

        public SupervisorV2ControlPlaneNetworkIpManagementIpAssignmentArgs build() {
            return $;
        }
    }

}
