// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.VSphere.Inputs
{

    public sealed class SupervisorV2ControlPlaneNetworkServicesGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The DNS configuration.
        /// </summary>
        [Input("dns")]
        public Input<Inputs.SupervisorV2ControlPlaneNetworkServicesDnsGetArgs>? Dns { get; set; }

        /// <summary>
        /// The NTP configuration.
        /// </summary>
        [Input("ntp")]
        public Input<Inputs.SupervisorV2ControlPlaneNetworkServicesNtpGetArgs>? Ntp { get; set; }

        public SupervisorV2ControlPlaneNetworkServicesGetArgs()
        {
        }
        public static new SupervisorV2ControlPlaneNetworkServicesGetArgs Empty => new SupervisorV2ControlPlaneNetworkServicesGetArgs();
    }
}
