// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The `vsphere.getVmfsDisks` data source can be used to discover the storage
 * devices available on an ESXi host. This data source can be combined with the
 * `vsphere.VmfsDatastore` resource to create VMFS
 * datastores based off a set of discovered disks.
 */
export function getVmfsDisks(args: GetVmfsDisksArgs, opts?: pulumi.InvokeOptions): Promise<GetVmfsDisksResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("vsphere:index/getVmfsDisks:getVmfsDisks", {
        "filter": args.filter,
        "hostSystemId": args.hostSystemId,
        "rescan": args.rescan,
    }, opts);
}

/**
 * A collection of arguments for invoking getVmfsDisks.
 */
export interface GetVmfsDisksArgs {
    /**
     * A regular expression to filter the disks against. Only
     * disks with canonical names that match will be included.
     *
     * > **NOTE:** Using a `filter` is recommended if there is any chance the host
     * will have any specific storage devices added to it that may affect the order of
     * the output `disks` attribute below, which is lexicographically sorted.
     */
    filter?: string;
    /**
     * The managed object ID of
     * the host to look for disks on.
     */
    hostSystemId: string;
    /**
     * Whether or not to rescan storage adapters before
     * searching for disks. This may lengthen the time it takes to perform the
     * search. Default: `false`.
     */
    rescan?: boolean;
}

/**
 * A collection of values returned by getVmfsDisks.
 */
export interface GetVmfsDisksResult {
    /**
     * A lexicographically sorted list of devices discovered by the
     * operation, matching the supplied `filter`, if provided.
     */
    readonly disks: string[];
    readonly filter?: string;
    readonly hostSystemId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly rescan?: boolean;
}
/**
 * The `vsphere.getVmfsDisks` data source can be used to discover the storage
 * devices available on an ESXi host. This data source can be combined with the
 * `vsphere.VmfsDatastore` resource to create VMFS
 * datastores based off a set of discovered disks.
 */
export function getVmfsDisksOutput(args: GetVmfsDisksOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetVmfsDisksResult> {
    return pulumi.output(args).apply((a: any) => getVmfsDisks(a, opts))
}

/**
 * A collection of arguments for invoking getVmfsDisks.
 */
export interface GetVmfsDisksOutputArgs {
    /**
     * A regular expression to filter the disks against. Only
     * disks with canonical names that match will be included.
     *
     * > **NOTE:** Using a `filter` is recommended if there is any chance the host
     * will have any specific storage devices added to it that may affect the order of
     * the output `disks` attribute below, which is lexicographically sorted.
     */
    filter?: pulumi.Input<string>;
    /**
     * The managed object ID of
     * the host to look for disks on.
     */
    hostSystemId: pulumi.Input<string>;
    /**
     * Whether or not to rescan storage adapters before
     * searching for disks. This may lengthen the time it takes to perform the
     * search. Default: `false`.
     */
    rescan?: pulumi.Input<boolean>;
}
